<?php
// $Id$
/*
Bulk stock updater module for Drupal 
Copyright (C) 2010 Ramesh Nair (www.hiddentao.com)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * @file
 * The Ubercart stock updater module.
 *
 * Provides the facility to bulk-edit product stock levels.
 */

/******************************************************************************
 * Drupal Hooks                                                               *
 ******************************************************************************/
define('_UC_BULK_STOCK_UPDATER_MENU_OVERVIEW','admin/store/stock');
define('_UC_BULK_STOCK_UPDATER_MENU_UPDATE','admin/store/stock/update');
define('_UC_BULK_STOCK_UPDATER_MENU_UPDATE_AJAX','admin/store/stock/update/ajax');

/**
 * Implementation of hook_menu().
 */
function uc_bulk_stock_updater_menu() {
  $items = array();

  $items[_UC_BULK_STOCK_UPDATER_MENU_OVERVIEW] = array(
    'title' => t('Stock'),
    'description' => t('Administer stock levels.'),
    'access arguments' => array('administer products'),
    'page callback' => 'uc_bulk_stock_updater_stock_overview',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -2,
    'file' => 'uc_bulk_stock_updater.inc',
  );
  $items[_UC_BULK_STOCK_UPDATER_MENU_UPDATE] = array(
    'title' => t('Bulk update'),
    'description' => t('Bulk-update stock levels.'),
    'access arguments' => array('administer products'),
    'page callback' => 'uc_bulk_stock_updater_stock_update',
  	'type' => MENU_NORMAL_ITEM,
    'weight' => -10,
    'file' => 'uc_bulk_stock_updater.inc',
  );
  $items[_UC_BULK_STOCK_UPDATER_MENU_UPDATE_AJAX] = array(
    'access arguments' => array('administer products'),
    'page callback' => 'uc_bulk_stock_updater_stock_update_ajax',
  	'type' => MENU_CALLBACK,
    'file' => 'uc_bulk_stock_updater.inc',
  );
  
  return $items;
}


/**
 * Implementation of hook_help().
 */
function uc_bulk_stock_updater_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/settings/module#description':
      	$output .= t('Bulk-edit product stock levels.');
      	break;
    case 'admin/store/stock':
    case 'admin/store/stock/update':
    	$output .= t('The stock levels will get submitted and saved to the server as you edit them.');
    	break;
    default:
      $output = '';
      break;
  }
  return $output;
}

