<?php
// $Id$

/**
 * @file
 * The Ubercart stock updater module.
 *
 * Provides the facility to bulk-edit product stock levels.
 */


// url paths
define('_UC_BULK_STOCK_UPDATER_MENU_OVERVIEW', 'admin/store/stock');
define('_UC_BULK_STOCK_UPDATER_MENU_UPDATE', 'admin/store/stock/update');
define('_UC_BULK_STOCK_UPDATER_MENU_UPDATE_AJAX', 'admin/store/stock/update/ajax');

// permissions
define('_UC_BULK_STOCK_UPDATER_PERM_BULK_UPDATE_STOCK', 'bulk update stock');



/**
 * Implementation of hook_menu().
 */
function uc_bulk_stock_updater_menu() {
  $items = array();

  $items[_UC_BULK_STOCK_UPDATER_MENU_OVERVIEW] = array(
    'title' => 'Stock',
    'description' => 'Administer stock levels.',
    'access arguments' => _UC_BULK_STOCK_UPDATER_PERM_BULK_UPDATE_STOCK,
    'page callback' => 'uc_bulk_stock_updater_stock_overview',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -2,
    'file' => 'uc_bulk_stock_updater.inc',
  );
  $items[_UC_BULK_STOCK_UPDATER_MENU_UPDATE] = array(
    'title' => 'Bulk update',
    'description' => 'Bulk-update stock levels.',
    'access arguments' => _UC_BULK_STOCK_UPDATER_PERM_BULK_UPDATE_STOCK,
    'page callback' => 'uc_bulk_stock_updater_stock_update',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -10,
    'file' => 'uc_bulk_stock_updater.inc',
  );
  $items[_UC_BULK_STOCK_UPDATER_MENU_UPDATE_AJAX] = array(
    'access arguments' => _UC_BULK_STOCK_UPDATER_PERM_BULK_UPDATE_STOCK,
    'page callback' => 'uc_bulk_stock_updater_stock_update_ajax',
    'type' => MENU_CALLBACK,
    'file' => 'uc_bulk_stock_updater.inc',
  );
  
  return $items;
}

/**
 * Implementation of hook_perm()
 */
function uc_bulk_stock_updater_perm() {
	return array(_UC_BULK_STOCK_UPDATER_PERM_BULK_UPDATE_STOCK);
}

/**
 * Implementation of hook_help().
 */
function uc_bulk_stock_updater_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/settings/module#description':
      	$output .= t('Bulk-edit product stock levels.');
      	break;
    case 'admin/store/stock':
    case 'admin/store/stock/update':
    	$output .= t('The stock levels will get submitted and saved to the server as you edit them.');
    	break;
    default:
      $output = '';
      break;
  }
  return $output;
}

